### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by rabernat**
This updates the website with the following changes:
- Officially calls the group the **The Pangeo / ESGF Cloud Data Working Group**
- Provides information about meeting schedule
- Changes the theme

cc aradhakrishnanGFDL, @agstephens

### CODE REVIEW

**Review by aradhakrishnanGFDL — CHANGES_REQUESTED** [review]
Hi @rabernat This is great. Thank you.

Few suggestions (can be tabled for second version after the page is live if appropriate)

1. NetCDF data overview section- for pointers to NetCDF CMIP6 bucket and catalogs
2. Other documentation section: Links to pangeo youtube channel (or placeholders for slides,etc)
3. Under the CMIP6 bullet, another sub-bullet for Data citation recommendation. 
4.  Member names could be added as well, after checking with the individuals. But, I understand this list can grow and the page maintenance can be an issue later on.

**Comment by rabernat** [comment]
Thanks for the feedback Aparna! All of these things are doable, but I think they should be done as separate, atomic updates.

> 1. NetCDF data overview section- for pointers to NetCDF CMIP6 bucket and catalogs

Would you be willing to write this?

> 2. Other documentation section: Links to pangeo youtube channel (or placeholders for slides,etc)

Great idea. Hopefully someone else can contribute this.

> 3. Under the CMIP6 bullet, another sub-bullet for Data citation recommendation.

Great idea. Would you be willing to make a PR for this?

> 4. Member names could be added as well, after checking with the individuals. But, I understand this list can grow and the page maintenance can be an issue later on.

Based on experience with Pangeo, I think maintaining a list of participants in such an open group is not sustainable. We could list participating institutions.

**Comment by aradhakrishnanGFDL** [comment]
> Thanks for the feedback Aparna! All of these things are doable, but I think they should be done as separate, atomic updates.
> 
> > 1. NetCDF data overview section- for pointers to NetCDF CMIP6 bucket and catalogs
> Would you be willing to write this?

Yes.
> 
> > 2. Other documentation section: Links to pangeo youtube channel (or placeholders for slides,etc)
> 
> Great idea. Hopefully someone else can contribute this.
> 
> > 3. Under the CMIP6 bullet, another sub-bullet for Data citation recommendation.
> 
> Great idea. Would you be willing to make a PR for this?

Yes.
> 
> > 4. Member names could be added as well, after checking with the individuals. But, I understand this list can grow and the page maintenance can be an issue later on.
> 
> Based on experience with Pangeo, I think maintaining a list of participants in such an open group is not sustainable. We could list participating institutions.

Sounds good!

**Comment by rabernat** [comment]
Ok, so this is now merged. I welcome PRs to add more details as discussed above.

**Pull request merged**
